import type { LessonDefinition } from '@/features/lessons/lessonTypes';

export const ledCurrentLimitingLesson: LessonDefinition = {
  id: 'lesson-led-current-limiter',
  slug: 'led-current-limiting',
  title: 'Verse 2 · LED Current Limiting',
  subtitle: 'Build a safe LED loop, inspect live current flow, then break it to learn why it fails.',
  conceptTitle: 'LED Current Limiting',
    track: 'foundations',
  difficulty: 'beginner',
  estimatedMinutes: 12,
  requiredComponents: ['battery-source', 'resistor', 'led'],
  optionalComponents: ['multimeter', 'spst-switch'],
  recommendedStartingBoardState: 'Start from a clean board. Guided mode will highlight each placement and wire endpoint.',
  learningObjectives: [
    'Build +V → resistor → LED → GND as a deliberate series path.',
    'Explain why the resistor must remain in the active LED current path.',
    'Use flow and diagnostics to compare working, reversed, and open-loop states.',
  ],
  buildGoal: 'Create a complete, resistor-limited LED loop, verify flow direction, then run break-it experiments to compare outcomes.',
  steps: [
    {
      id: 'led-intro',
      type: 'intro',
      title: 'Understand today’s build',
      guidance: 'You are building one safe series path: source + → resistor → LED → source –. Guided mode will show exactly what to do next.',
      supportGuidance: {
        guided: 'Review the goal on the postcard, then follow each highlighted action in order.',
        coached: 'Plan a series current path with a resistor and correctly oriented LED.',
        independent: 'Build the loop and be ready to justify polarity + current limiting.',
      },
      overlayTargets: [{ id: 'led-lib-resistor', type: 'component-library-item', componentType: 'resistor', label: 'Start with resistor' }],
    },
    {
      id: 'led-place-resistor',
      type: 'place_component',
      title: 'Place the resistor',
      successCondition: 'A resistor is placed across the trench in the guided zone.',
      primaryHighlightTargetId: 'led-lib-resistor-2',
      secondaryHintTargetId: 'led-res-zone',
      teachingNote: 'A resistor limits current so the LED stays in a safe operating range.',
      afterStepTeachingNote: 'Nice placement. This resistor will protect the LED once current starts flowing.',
      guidance: 'Place the resistor across the center trench in the highlighted row zone.',
      supportGuidance: {
        guided: 'Pick resistor in the library, then place it across rows 8–10 in the highlighted zone.',
      },
      overlayTargets: [
        { id: 'led-lib-resistor-2', type: 'component-library-item', componentType: 'resistor', label: 'Choose resistor' },
        { id: 'led-res-zone', type: 'breadboard-zone', zone: { fromHoleId: 'left-b-8', toHoleId: 'left-g-8' }, label: 'Resistor span' },
        { id: 'led-res-left', type: 'breadboard-hole', holeId: 'left-b-8', label: 'Resistor leg A' },
        { id: 'led-res-right', type: 'breadboard-hole', holeId: 'left-g-8', label: 'Resistor leg B' },
      ],
    },
    {
      id: 'led-place-led',
      type: 'place_component',
      title: 'Place the LED with correct polarity',
      successCondition: 'LED is placed with anode toward resistor side and cathode toward return side.',
      primaryHighlightTargetId: 'led-lib-led',
      secondaryHintTargetId: 'led-led-zone',
      teachingNote: 'LEDs conduct in one direction, so orientation is part of the circuit logic.',
      afterStepTeachingNote: 'Great. LED polarity is now set for forward conduction.',
      guidance: 'Place LED so anode (long leg) can connect from resistor and cathode can return to ground rail.',
      supportGuidance: {
        guided: 'Place LED across the trench in row 10. Keep anode on the resistor side and cathode on the return side.',
      },
      overlayTargets: [
        { id: 'led-lib-led', type: 'component-library-item', componentType: 'led', label: 'Choose LED next' },
        { id: 'led-led-zone', type: 'breadboard-zone', zone: { fromHoleId: 'left-d-10', toHoleId: 'left-h-10' }, label: 'LED span' },
        { id: 'led-led-anode', type: 'breadboard-hole', holeId: 'left-d-10', label: 'LED anode (+)' },
        { id: 'led-led-cathode', type: 'breadboard-hole', holeId: 'left-h-10', label: 'LED cathode (–)' },
      ],
    },
    {
      id: 'led-wire-supply',
      type: 'wire_connection',
      title: 'Connect source + to resistor',
      successCondition: 'A wire connects top positive rail to resistor input leg.',
      primaryHighlightTargetId: 'led-wire-plus-start',
      secondaryHintTargetId: 'led-wire-plus-end',
      guidance: 'Wire from the top positive rail to the resistor input leg.',
      supportGuidance: {
        guided: 'In wire mode, start at + rail and end at resistor leg A.',
      },
      overlayTargets: [
        { id: 'led-wire-plus-start', type: 'wire-start', holeId: 'rail-top-positive-6', label: 'Start at + rail' },
        { id: 'led-wire-plus-end', type: 'wire-end', holeId: 'left-b-8', label: 'End at resistor input' },
      ],
    },
    {
      id: 'led-wire-series-link',
      type: 'wire_connection',
      title: 'Connect resistor output to LED anode',
      successCondition: 'A wire links resistor output directly to LED anode.',
      primaryHighlightTargetId: 'led-wire-mid-start',
      secondaryHintTargetId: 'led-wire-mid-end',
      guidance: 'Link the resistor output leg to LED anode so the resistor stays in series.',
      supportGuidance: {
        guided: 'Start wire at resistor leg B, then end at LED anode.',
      },
      overlayTargets: [
        { id: 'led-wire-mid-start', type: 'wire-start', holeId: 'left-g-8', label: 'Start resistor output' },
        { id: 'led-wire-mid-end', type: 'wire-end', holeId: 'left-d-10', label: 'End at LED anode' },
      ],
    },
    {
      id: 'led-wire-return',
      type: 'wire_connection',
      title: 'Complete the return path to ground',
      successCondition: 'A wire returns from LED cathode to negative rail, closing the loop.',
      primaryHighlightTargetId: 'led-wire-return-start',
      secondaryHintTargetId: 'led-wire-return-end',
      afterStepTeachingNote: 'Closed path complete: current can now move through the full loop.',
      guidance: 'Connect LED cathode to the top negative rail to close the loop.',
      supportGuidance: {
        guided: 'Start at LED cathode and end at – rail. This closes the loop.',
      },
      overlayTargets: [
        { id: 'led-wire-return-start', type: 'wire-start', holeId: 'left-h-10', label: 'Start LED cathode' },
        { id: 'led-wire-return-end', type: 'wire-end', holeId: 'rail-top-negative-8', label: 'End at – rail' },
      ],
    },
    {
      id: 'led-run',
      type: 'run_simulation',
      title: 'Run and inspect closed-loop flow',
      successCondition: 'Simulation runs and flow view is enabled for the active loop.',
      primaryHighlightTargetId: 'led-flow-tool',
      toolSuggestion: 'Open instruments',
      guidance: 'Run simulation and turn on flow. You should see one active path through resistor and LED.',
      observationHint: 'Observe where flow starts, where it passes through resistor and LED, and where it returns.',
      overlayTargets: [{ id: 'led-flow-tool', type: 'panel-control', panelControlId: 'flow-toggle', label: 'Turn on flow' }],
    },
    {
      id: 'led-break',
      type: 'break_circuit',
      title: 'Break it: reverse LED or open return',
      successCondition: 'A controlled break is applied and re-run to compare behavior.',
      primaryHighlightTargetId: 'led-break-zone',
      afterStepTeachingNote: 'Exactly: a broken path means current can’t sustain through the LED branch.',
      guidance: 'Now intentionally break the loop. Reverse LED orientation OR remove return wire and rerun.',
      expectedOutcome: 'Flow becomes blocked or open; diagnostics should describe why current path is invalid.',
      overlayTargets: [{ id: 'led-break-zone', type: 'breadboard-zone', zone: { fromHoleId: 'left-d-10', toHoleId: 'left-h-10' }, label: 'Try LED reversal here' }],
    },
    {
      id: 'led-compare',
      type: 'observe_behavior',
      title: 'Compare resistor values',
      guidance: 'Set resistor to 330 Ω, then 1 kΩ, and compare flow intensity/brightness behavior.',
      observationHint: 'Higher resistance reduces current in the same path.',
    },
    {
      id: 'led-complete',
      type: 'complete',
      title: 'Explain your takeaway',
      guidance: 'State why LED polarity and a series resistor are both required in a closed loop.',
    },
  ],
  observations: [
    'When the loop is closed and polarity is correct, flow traces a continuous source-to-ground path.',
    'The resistor remains inside the active path; it is not optional decoration.',
    'Reversing LED polarity or opening return path visibly breaks meaningful current flow.',
    'Increasing resistance lowers current and should reduce observed intensity.',
  ],
  breakExperiments: [
    {
      id: 'led-reverse-led',
      title: 'Reverse LED polarity',
      prompt: 'Flip the LED orientation and rerun. Compare flow and LED behavior to the working case.',
      expectedLearning: 'Correct polarity is required for forward current through the LED branch.',
    },
    {
      id: 'led-open-return',
      title: 'Open the return path',
      prompt: 'Disconnect the cathode return wire to ground and inspect where the path stops.',
      expectedLearning: 'Without a complete loop back to source, current cannot sustain.',
    },
    {
      id: 'led-change-resistor',
      title: 'Change resistor value',
      prompt: 'Compare 330 Ω vs 1 kΩ and observe current/brightness difference in the same topology.',
      expectedLearning: 'Series resistance sets current magnitude and protects the LED.',
    },
  ],
  explanationPrompts: [
    'How can I confirm this is a closed loop and not just connected-looking wires?',
    'How does resistor value change LED current in this exact circuit?',
  ],
  commonMistakes: [
    'LED is reversed so forward conduction is blocked.',
    'Return wire to ground is missing, leaving an open loop.',
    'Resistor is bypassed or moved out of the intended series path.',
  ],
  checkpoints: [
    { id: 'cp-led-components', type: 'components_placed', label: 'Required components placed', description: 'Source, resistor, and LED are on the board.' },
    { id: 'cp-led-topology', type: 'topology_connected', label: 'Series path connected', description: 'Intended + → resistor → LED → ground path is assembled.' },
    { id: 'cp-led-run', type: 'simulation_run', label: 'Simulation observed', description: 'Simulation was run to inspect behavior.' },
    { id: 'cp-led-break', type: 'break_experiment', label: 'Break-it experiment completed', description: 'At least one controlled break-it experiment was attempted.' },
    { id: 'cp-led-explain', type: 'explanation_acknowledged', label: 'Concept explained', description: 'Lesson was completed with concept explanation.' },
  ],
  tutorPromptHints: [
    'Why isn’t my LED turning on?',
    'What does the resistor do in this loop?',
    'How can I tell if my loop is complete?',
    'What changes if I reverse the LED?',
    'Why does changing resistor value matter?',
  ],
  tags: ['foundations', 'led', 'current-limiting', 'guided-golden-path'],
  relatedComponents: ['battery-source', 'resistor', 'led'],
  professionalToolRecommendations: ['Postcard', 'Flow view', 'Diagnostics', 'Tutor'],
};
