import type { LessonDefinition } from '@/features/lessons/lessonTypes';

export const ledCurrentLimitingLesson: LessonDefinition = {
  id: 'lesson-led-current-limiter',
  slug: 'led-current-limiting',
  title: 'Verse 2 · Protect the LED',
  subtitle: 'Build a complete loop and protect the LED with a series resistor.',
  conceptTitle: 'LED Current Limiting',
  conceptSummary: 'LEDs need direction and current limiting; a series resistor keeps current in a safe range.',
  difficulty: 'beginner',
  estimatedMinutes: 14,
  requiredComponents: ['battery-source', 'resistor', 'led'],
  optionalComponents: ['spst-switch', 'multimeter'],
  recommendedStartingBoardState: 'Start from a clean board so every connection is intentional.',
  learningObjectives: ['Confirm current only flows when a full loop exists.', 'Verify LED polarity by testing reversed orientation.', 'Compare brightness/current change with 330 Ω vs 1 kΩ.'],
  buildGoal: 'Build +V → resistor → LED → GND, then compare behavior after controlled break-it changes.',
  steps: [
    { id: 'led-intro', type: 'intro', title: 'Read the goal', guidance: 'You need a closed loop and correct LED direction before anything lights.' },
    { id: 'led-build', type: 'wire_connection', title: 'Build the safe loop', guidance: 'Wire source + to resistor, resistor to LED anode, LED cathode to ground.', supportGuidance: { guided: 'Place the resistor and LED using the highlighted locations, then connect + → resistor → LED → ground exactly.', coached: 'Build a series path with source, resistor, and LED. Keep LED polarity and return path in mind.', independent: 'Create a safe LED loop and prepare to justify why the resistor is in series.' }, overlayTargets: [{ id: 'led-lib-resistor', type: 'component-library-item', componentType: 'resistor', label: 'Pick resistor next' }, { id: 'led-hole-r-plus', type: 'breadboard-hole', holeId: 'rail-top-positive-6', label: '+ source side' }, { id: 'led-zone-series', type: 'breadboard-zone', zone: { fromHoleId: 'left-b-8', toHoleId: 'left-d-10' }, label: 'Series build zone' }, { id: 'led-wire-end', type: 'wire-end', holeId: 'rail-top-negative-8', label: 'Return to ground' }] },
    { id: 'led-run', type: 'run_simulation', title: 'Run simulation', guidance: 'Confirm active flow through both resistor and LED.' },
    { id: 'led-probe', type: 'probe_node', title: 'Probe key nodes', guidance: 'Probe before/after resistor and at LED cathode to verify voltage drop.', overlayTargets: [{ id: 'led-probe-node', type: 'node', holeId: 'left-c-9', label: 'Probe midpoint node' }] },
    { id: 'led-break', type: 'break_circuit', title: 'Break it on purpose', guidance: 'Try one: remove resistor, reverse LED, or open return path.', expectedOutcome: 'Diagnostics should explain why the LED is unsafe/off/open.' },
    { id: 'led-compare', type: 'observe_behavior', title: 'Compare resistor values', guidance: 'Use 330 Ω and 1 kΩ, then compare flow intensity/brightness.' },
    { id: 'led-complete', type: 'complete', title: 'Explain the result', guidance: 'Summarize why a resistor is mandatory in LED circuits.' },
  ],
  observations: ['Flow should highlight a complete path only when the return path is connected.', 'Reversing LED orientation blocks useful current and the LED stays dark.', 'Raising resistor value lowers current and dims the LED.'],
  breakExperiments: [
    { id: 'led-no-resistor', title: 'Remove resistor', prompt: 'Temporarily bypass/remove the resistor and read the warning.', expectedLearning: 'A bare LED path is an unsafe design even if it appears to light.' },
    { id: 'led-reverse-led', title: 'Reverse LED', prompt: 'Flip LED polarity and rerun simulation.', expectedLearning: 'Direction matters: diode orientation controls conduction.' },
    { id: 'led-open-return', title: 'Open return path', prompt: 'Disconnect LED return from ground.', expectedLearning: 'No closed loop means no current, regardless of source voltage.' },
  ],
  explanationPrompts: ['How can I verify my LED path is a complete loop?', 'Why does a series resistor protect the LED?'],
  commonMistakes: ['Resistor placed in parallel instead of series.', 'LED cathode/anode reversed.', 'Return path disconnected from ground.'],
  checkpoints: [
    { id: 'cp-led-components', type: 'components_placed', label: 'Required components placed', description: 'Source, resistor, LED are placed.' },
    { id: 'cp-led-topology', type: 'topology_connected', label: 'Series path connected', description: 'Circuit is connected well enough to run.' },
    { id: 'cp-led-run', type: 'simulation_run', label: 'Simulation run', description: 'Run or step simulation to observe behavior.' },
    { id: 'cp-led-probe', type: 'node_probed', label: 'Node probed', description: 'A lesson node has been measured.' },
    { id: 'cp-led-break', type: 'break_experiment', label: 'Break-it completed', description: 'At least one break-it experiment was attempted.' },
  ],
  tutorPromptHints: ['Why is my LED not turning on?', 'What happens if I remove the resistor?', 'How can I tell if the loop is complete?'],
  tags: ['foundations', 'led', 'current-limiting'],
  relatedComponents: ['resistor', 'led', 'battery-source'],
  professionalToolRecommendations: ['Instruments', 'Flow view', 'Tutor'],
};
