import type { LessonDefinition } from '@/features/lessons/lessonTypes';

export const ledCurrentLimitingLesson: LessonDefinition = {
  id: 'lesson-led-current-limiter',
  slug: 'led-current-limiting',
  title: 'Verse 2 · LED Current Limiting',
  subtitle: 'Build a safe LED loop, inspect live current flow, then break it to learn why it fails.',
  conceptTitle: 'LED Current Limiting',
  conceptSummary: 'Current should move from + rail through resistor and LED before returning to ground.',
  track: 'foundations',
  difficulty: 'beginner',
  estimatedMinutes: 12,
  requiredComponents: ['battery-source', 'resistor', 'led'],
  optionalComponents: ['multimeter', 'spst-switch'],
  recommendedStartingBoardState: 'Start from a clean board. Guided mode will highlight each placement and wire endpoint.',
  learningObjectives: [
    'Build +V → resistor → LED → GND as a deliberate series path.',
    'Explain why the resistor must remain in the active LED current path.',
    'Use flow and diagnostics to compare working, reversed, and open-loop states.',
  ],
  buildGoal: 'Create a complete, resistor-limited LED loop, verify flow direction, then run break-it experiments to compare outcomes.',
  blueprint: {
    id: 'bp-led-current-limit-v1',
    title: 'Target LED current-limiting loop',
    components: [
      {
        lessonComponentId: 'resistor-main',
        componentType: 'resistor',
        label: 'Series resistor',
        targetPlacement: { terminalHoleMap: { terminalA: 'left-b-8', terminalB: 'left-g-8' } },
        properties: { resistanceOhms: 330 },
      },
      {
        lessonComponentId: 'led-main',
        componentType: 'led',
        label: 'LED',
        targetPlacement: { terminalHoleMap: { anode: 'left-d-10', cathode: 'left-h-10' } },
      },
    ],
    connections: [
      {
        id: 'wire-vplus-to-resistor',
        kind: 'wire',
        label: '+ rail to resistor',
        from: { holeId: 'rail-top-positive-6' },
        to: { componentId: 'resistor-main', terminal: 'terminalA' },
      },
      {
        id: 'wire-resistor-to-led',
        kind: 'wire',
        label: 'Resistor to LED anode',
        from: { componentId: 'resistor-main', terminal: 'terminalB' },
        to: { componentId: 'led-main', terminal: 'anode' },
      },
      {
        id: 'wire-led-to-ground',
        kind: 'wire',
        label: 'LED cathode to ground rail',
        from: { componentId: 'led-main', terminal: 'cathode' },
        to: { holeId: 'rail-top-negative-8' },
      },
    ],
    observationTargets: [
      { id: 'target-main-path', type: 'path', label: 'Main current path', targetRef: { from: 'rail-top-positive-6', to: 'rail-top-negative-8' } },
    ],
    breakTargets: [
      { id: 'break-reverse-led', type: 'reverse_component', label: 'Reverse LED', targetRef: { componentId: 'led-main' } },
      { id: 'break-remove-return', type: 'remove_connection', label: 'Open return wire', targetRef: { connectionId: 'wire-led-to-ground' } },
    ],
  },
  steps: [
    {
      id: 'led-inspect-target',
      type: 'inspect_target_circuit',
      actionType: 'inspect_target_circuit',
      title: 'Inspect the target circuit',
      guidance: 'Read the target path before building: + rail → resistor → LED → – rail.',
      teachingNote: 'Start with the full path in mind so each step has clear purpose.',
      inspectTargetCircuit: {
        summary: 'You are building one protected loop where current is limited before it reaches the LED.',
        pathOrder: ['+ rail', 'series resistor', 'LED anode→cathode', '– rail return'],
        focusComponentIds: ['resistor-main', 'led-main'],
      },
      supportGuidance: {
        guided: 'Scan the path preview, then start building from the + rail side.',
        coached: 'Identify the series order first, then place components to support that path.',
        independent: 'Confirm your target topology before placing parts.',
      },
      blueprintTargets: { observationTargetIds: ['target-main-path'], componentIds: ['resistor-main', 'led-main'] },
    },
    {
      id: 'led-place-resistor',
      type: 'place_component',
      actionType: 'place_component',
      title: 'Place the resistor',
      successCondition: 'Resistor is placed on the exact target holes.',
      teachingNote: 'This resistor will limit current through the LED.',
      afterStepTeachingNote: 'Nice placement. Current limiting is now physically built into the path.',
      guidance: 'Place the resistor across the highlighted holes.',
      supportGuidance: { guided: 'Choose resistor, then place terminalA at left-b-8 and terminalB at left-g-8.' },
      blueprintTargets: { componentIds: ['resistor-main'] },
    },
    {
      id: 'led-place-led',
      type: 'place_component',
      actionType: 'place_component',
      title: 'Place the LED with correct polarity',
      successCondition: 'LED anode and cathode match the target holes.',
      teachingNote: 'LEDs only conduct in one direction.',
      afterStepTeachingNote: 'Great. The LED orientation now matches the intended current direction.',
      guidance: 'Place the LED so anode is on the resistor side and cathode on return side.',
      supportGuidance: { guided: 'Place anode at left-d-10 and cathode at left-h-10.' },
      blueprintTargets: { componentIds: ['led-main'] },
    },
    {
      id: 'led-wire-supply',
      type: 'place_wire',
      actionType: 'place_wire',
      title: 'Connect power to resistor',
      successCondition: 'A wire connects + rail to resistor input.',
      guidance: 'Wire from + rail into resistor terminalA.',
      supportGuidance: { guided: 'Start at rail-top-positive-6 and end at left-b-8.' },
      blueprintTargets: { connectionIds: ['wire-vplus-to-resistor'] },
    },
    {
      id: 'led-wire-series-link',
      type: 'place_wire',
      actionType: 'place_wire',
      title: 'Connect resistor to LED anode',
      successCondition: 'A wire connects resistor output to LED anode.',
      guidance: 'Keep resistor in-series by wiring resistor output to LED anode.',
      supportGuidance: { guided: 'Start at left-g-8 and end at left-d-10.' },
      blueprintTargets: { connectionIds: ['wire-resistor-to-led'] },
    },
    {
      id: 'led-wire-return',
      type: 'place_wire',
      actionType: 'place_wire',
      title: 'Connect LED to ground',
      successCondition: 'Return wire closes the loop to negative rail.',
      afterStepTeachingNote: 'Now the circuit has a closed loop.',
      guidance: 'Wire LED cathode back to the – rail.',
      supportGuidance: { guided: 'Start at left-h-10 and end at rail-top-negative-8.' },
      blueprintTargets: { connectionIds: ['wire-led-to-ground'] },
    },
    {
      id: 'led-run',
      type: 'run_flow',
      actionType: 'run_flow',
      title: 'Observe the active path',
      successCondition: 'Simulation is running and flow is visible.',
      toolSuggestion: 'Open instruments',
      guidance: 'Run simulation and inspect the full active path through resistor then LED.',
      observationHint: 'Current should follow the same order as the target path preview.',
      blueprintTargets: { observationTargetIds: ['target-main-path'] },
      overlayTargets: [{ id: 'led-flow-tool', type: 'panel-control', panelControlId: 'flow-toggle', label: 'Turn on flow' }],
    },
    {
      id: 'led-break',
      type: 'break_circuit',
      actionType: 'break_circuit',
      title: 'Break it: reverse the LED',
      successCondition: 'LED orientation is changed from blueprint target orientation.',
      afterStepTeachingNote: 'Reversing the LED blocks the intended current path.',
      guidance: 'Reverse the LED orientation, then rerun simulation.',
      expectedOutcome: 'Flow should no longer follow the intended path.',
      blueprintTargets: { breakTargetIds: ['break-reverse-led'], componentIds: ['led-main'] },
    },
    {
      id: 'led-compare',
      type: 'compare_state',
      actionType: 'compare_state',
      title: 'Compare working vs broken state',
      guidance: 'Compare flow and diagnostics between normal orientation and reversed LED.',
      observationHint: 'The closed loop still exists physically, but diode polarity blocks current through LED branch.',
      toolSuggestion: 'Use diagnostics',
    },
    {
      id: 'led-complete',
      type: 'complete',
      actionType: 'complete',
      title: 'Complete lesson',
      guidance: 'State why resistor placement and LED polarity both matter in this loop.',
    },
  ],
  observations: [
    'When the loop is closed and polarity is correct, flow traces a continuous source-to-ground path.',
    'The resistor remains inside the active path; it is not optional decoration.',
    'Reversing LED polarity visibly breaks meaningful current flow.',
  ],
  breakExperiments: [
    {
      id: 'led-reverse-led',
      title: 'Reverse LED polarity',
      prompt: 'Flip the LED orientation and rerun. Compare flow and LED behavior to the working case.',
      expectedLearning: 'Correct polarity is required for forward current through the LED branch.',
    },
  ],
  explanationPrompts: [
    'How can I confirm this is a closed loop and not just connected-looking wires?',
    'How does resistor value change LED current in this exact circuit?',
  ],
  commonMistakes: [
    'LED is reversed so forward conduction is blocked.',
    'Return wire to ground is missing, leaving an open loop.',
    'Resistor is bypassed or moved out of the intended series path.',
  ],
  checkpoints: [
    { id: 'cp-led-components', type: 'components_placed', label: 'Required components placed', description: 'Source, resistor, and LED are on the board.' },
    { id: 'cp-led-topology', type: 'topology_connected', label: 'Series path connected', description: 'Intended + → resistor → LED → ground path is assembled.' },
    { id: 'cp-led-run', type: 'simulation_run', label: 'Simulation observed', description: 'Simulation was run to inspect behavior.' },
    { id: 'cp-led-break', type: 'break_experiment', label: 'Break-it experiment completed', description: 'At least one controlled break-it experiment was attempted.' },
    { id: 'cp-led-explain', type: 'explanation_acknowledged', label: 'Concept explained', description: 'Lesson was completed with concept explanation.' },
  ],
  tutorPromptHints: [
    'Why isn’t my LED turning on?',
    'What does the resistor do in this loop?',
    'How can I tell if my loop is complete?',
  ],
  tags: ['foundations', 'led', 'current-limiting', 'guided-golden-path'],
  relatedComponents: ['battery-source', 'resistor', 'led'],
  professionalToolRecommendations: ['Postcard', 'Flow view', 'Diagnostics', 'Tutor'],
};
