import type { LessonDefinition } from '@/features/lessons/lessonTypes';

export const rcChargeLesson: LessonDefinition = {
  id: 'lesson-rc-charge',
  slug: 'rc-charge-curve',
  title: 'Verse 4 · Charging in Time',
  subtitle: 'See voltage rise over time, not instantly, in a resistor-capacitor path.',
  conceptTitle: 'RC Charging',
  conceptSummary: 'A capacitor charges through a resistor with a curved voltage rise over time.',
  difficulty: 'intermediate',
  estimatedMinutes: 17,
  requiredComponents: ['battery-source', 'resistor', 'capacitor'],
  optionalComponents: ['spst-switch', 'multimeter'],
  recommendedStartingBoardState: 'Start with source and rails only.',
  learningObjectives: ['Identify charging path from source through resistor into capacitor node.', 'Observe a time-based voltage rise on the capacitor node.', 'Predict how larger/smaller R or C changes charge speed.'],
  buildGoal: 'Build an RC charging circuit, run simulation, then compare charging speed after changing R and C.',
  steps: [
    { id: 'rc-place', type: 'place_component', title: 'Place source, resistor, capacitor', guidance: 'Use ~10 µF capacitor and 1 kΩ resistor for a visible baseline.' },
    { id: 'rc-wire', type: 'wire_connection', title: 'Wire RC topology', guidance: 'Connect source → resistor → capacitor node, capacitor return to ground.', supportGuidance: { guided: 'Follow highlights: + rail to resistor, resistor to RC node, capacitor from RC node to ground.', coached: 'Build a resistor-fed capacitor node with a clean ground return.', independent: 'Assemble your RC charging path and prepare to validate behavior with instruments.' }, overlayTargets: [{ id: 'rc-lib-resistor', type: 'component-library-item', componentType: 'resistor', label: 'Resistor first' }, { id: 'rc-lib-capacitor', type: 'component-library-item', componentType: 'capacitor', label: 'Capacitor next' }, { id: 'rc-zone', type: 'breadboard-zone', zone: { fromHoleId: 'left-b-17', toHoleId: 'left-e-20' }, label: 'RC region' }, { id: 'rc-node', type: 'node', holeId: 'left-d-18', label: 'Probe RC node' }] },
    { id: 'rc-run', type: 'run_simulation', title: 'Run simulation', guidance: 'Observe changing node voltage over time.' },
    { id: 'rc-observe', type: 'observe_behavior', title: 'Inspect trend panel', guidance: 'Voltage should rise quickly at first, then flatten toward source voltage.' },
    { id: 'rc-break', type: 'break_circuit', title: 'Compare timing variants', guidance: 'Increase/decrease R and C, reset, and compare charging speed.' },
    { id: 'rc-complete', type: 'complete', title: 'Complete', guidance: 'Capture what changes when R or C increases.' },
  ],
  observations: ['Capacitor node voltage rises over time rather than jumping instantly.', 'Larger resistor slows charging; smaller resistor speeds it up.', 'Larger capacitor slows charging because more charge is required.'],
  breakExperiments: [
    { id: 'rc-r-large', title: 'Increase resistor', prompt: 'Raise resistor value and rerun simulation.', expectedLearning: 'Higher resistance lowers charging current and increases charge time.' },
    { id: 'rc-c-large', title: 'Increase capacitor', prompt: 'Raise capacitor value and compare rise time.', expectedLearning: 'Larger capacitance increases time constant and slows voltage rise.' },
    { id: 'rc-reset-compare', title: 'Reset and compare', prompt: 'Reset lesson state and run baseline again for side-by-side comparison.', expectedLearning: 'Comparison makes time-domain behavior easier to understand.' },
  ],
  explanationPrompts: ['Why does this node rise slowly instead of instantly?', 'How do R and C together set charging speed?'],
  commonMistakes: ['Capacitor legs placed on same strip (no real component across nodes).', 'Missing resistor in charging path.', 'Expecting a linear ramp instead of an exponential-like curve.'],
  checkpoints: [
    { id: 'cp-rc-components', type: 'components_placed', label: 'RC components placed', description: 'Source, resistor, capacitor are present.' },
    { id: 'cp-rc-topology', type: 'topology_connected', label: 'RC topology connected', description: 'Source-resistor-capacitor-ground path is connected.' },
    { id: 'cp-rc-run', type: 'simulation_run', label: 'Simulation run', description: 'Simulation status is running or stepped.' },
    { id: 'cp-rc-probe', type: 'node_probed', label: 'Dynamic node observed', description: 'Capacitor node or related node has been probed.' },
    { id: 'cp-rc-break', type: 'break_experiment', label: 'RC comparison attempted', description: 'At least one R/C variation experiment was performed.' },
  ],
  tutorPromptHints: ['Why does this voltage rise slowly?', 'What happens if I use a larger resistor?', 'What changes when I increase the capacitor?'],
  tags: ['timing', 'rc'],
  relatedComponents: ['resistor', 'capacitor', 'battery-source'],
  professionalToolRecommendations: ['Waveform panel', 'Instruments', 'Flow view'],
};
