import type { LessonDefinition } from '@/features/lessons/lessonTypes';

export const voltageDividerLesson: LessonDefinition = {
  id: 'lesson-voltage-divider',
  slug: 'voltage-divider',
  title: 'Verse 3 · Split Voltage',
  subtitle: 'Use two resistors in series to produce a controllable midpoint voltage.',
  conceptTitle: 'Voltage Divider',
  conceptSummary: 'Series resistors divide source voltage in proportion to resistance.',
  difficulty: 'beginner',
  estimatedMinutes: 16,
  requiredComponents: ['battery-source', 'resistor', 'resistor'],
  optionalComponents: ['multimeter', 'led'],
  recommendedStartingBoardState: 'Empty board or previous lesson cleared.',
  learningObjectives: ['Identify supply, midpoint, and ground nodes.', 'Predict midpoint movement from resistor ratio.', 'Diagnose floating/open divider failures.'],
  buildGoal: 'Build a valid divider, probe midpoint voltage, then change R1/R2 to see the ratio shift.',
  steps: [
    { id: 'div-place', type: 'place_component', title: 'Place two resistors in series', guidance: 'Ensure midpoint node is accessible for probing.' },
    { id: 'div-wire', type: 'wire_connection', title: 'Connect to source rails', guidance: 'Top to +, bottom to ground.' },
    { id: 'div-probe', type: 'probe_node', title: 'Probe midpoint', guidance: 'Measure divider output node.' },
    { id: 'div-observe', type: 'observe_behavior', title: 'Adjust ratio', guidance: 'Make R1 much larger, then R2 much larger, and compare midpoint voltage.' },
    { id: 'div-break', type: 'break_circuit', title: 'Break one leg', guidance: 'Remove upper or lower resistor connection to create a floating/invalid midpoint.' },
    { id: 'div-complete', type: 'complete', title: 'Complete', guidance: 'Confirm output follows resistor ratio trend.' },
  ],
  observations: ['Equal resistors should put midpoint near half of supply.', 'Making R1 larger lowers midpoint; making R2 larger raises midpoint.', 'Removing either leg breaks true divider behavior and can leave midpoint floating.'],
  breakExperiments: [
    { id: 'div-r1-large', title: 'Increase R1', prompt: 'Make upper resistor much larger than lower resistor.', expectedLearning: 'Midpoint moves down toward ground.' },
    { id: 'div-r2-large', title: 'Increase R2', prompt: 'Make lower resistor much larger than upper resistor.', expectedLearning: 'Midpoint moves up toward supply.' },
    { id: 'div-open-lower', title: 'Open lower leg', prompt: 'Disconnect lower resistor from ground and inspect node state.', expectedLearning: 'Midpoint is no longer a valid divider output.' },
  ],
  explanationPrompts: ['Why is the middle node not at full supply?', 'How does the resistor ratio set midpoint voltage?'],
  commonMistakes: ['Resistors accidentally wired in parallel.', 'Midpoint probe placed on wrong row.', 'One divider leg left unconnected.'],
  checkpoints: [
    { id: 'cp-div-components', type: 'components_placed', label: 'Divider built', description: 'At least two resistors and source present.' },
    { id: 'cp-div-topology', type: 'topology_connected', label: 'Divider topology connected', description: 'Series divider path is connected and runnable.' },
    { id: 'cp-div-probe', type: 'node_probed', label: 'Midpoint measured', description: 'User probed any node during lesson.' },
    { id: 'cp-div-break', type: 'break_experiment', label: 'Break-it tried', description: 'A divider break experiment was completed.' },
  ],
  tutorPromptHints: ['Why is the middle node not at full voltage?', 'What happens if I change R1 or R2?', 'Why is this node floating now?'],
  tags: ['foundations', 'voltage-divider'],
  relatedComponents: ['resistor', 'battery-source'],
  professionalToolRecommendations: ['Instruments', 'Explain panel'],
};
